stages:
  - prepare
  - check
  - cypress

.: &common
  except:
    - tags
    - triggers
  tags:
    - NONPROD
  cache: &cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

install:
  stage: prepare
  script: npm install
  <<: *common
  cache:
    <<: *cache
    policy: pull-push

lint:
  stage: check
  script: npm run lint
  <<: *common

test:
  stage: check
  script: npm run test
  <<: *common

tsc:
  stage: check
  script: npm run tsc
  <<: *common

cypress:
  image: nexus.esphere.local:5000/ledacy:275
  stage: cypress
  script:
    - npm install
    - npm run cypress-ci
  <<: *common
  tags:
    - cypress
  cache:
    <<: *cache
    policy: pull-push
  variables:
    GIT_CLEAN_FLAGS: -fx -e node_modules/
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - cypress/screenshots/
      - cypress/videos/
